history: 1
task : "test"

# evaluater Configuration
evaluator:
  instructions: 

evaluatee:
  #model: "gpt-4o"
  model: "solar-pro2"
  instructions: |
    Please answer the following questions to the best of your ability. 
    You will be evaluated based on your responses. 

# Logging Configuration
logging:
  save_to_file: true
  output_dir: "logs"
  filename_template: "evaluate_{timestamp}.log"


# Logging Configuration
saver:
  save_to_file: true
  output_dir: "results"
  filename_template: "evaluate_{timestamp}.log"


self_refine: true
self_refine_loops: 3
slice_ref_for_violations: true
slice_max_per_type: 20   # 필요시 조절 : top 20만 보여줌